name: morpheus_launcher_gui
description: The center of your minecraft

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  flutter_acrylic:
    # When depending on this package from a real application you should use:
    #   flutter_acrylic: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  material_color_utilities: any
  bitsdojo_window_macos: 0.1.3
  flutter_localization: any
  cached_network_image: any
  simple_3d_renderer: any
  shared_preferences: any
  flutter_markdown: any
  dropdown_button2: any
  bitsdojo_window: ^0.1.5
  flutter_switch: any
  file_selector: any
  url_launcher: any
  system_theme: any
  flutter_html: any
  text_divider: any
  file_picker: any
  process_run: any
  http_parser: any
  provider: any
  archive: any
  encrypt: 5.0.1
  crypto: 3.0.2
  image: any
  http: any
  intl: any
  blur: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/alex.png
    - assets/steve.png
    - assets/morpheus.png
    - assets/morpheus-animated.gif
    - assets/alex-raw.png
    - assets/steve-raw.png

  fonts:
    - family: MorpheusIcons
      fonts:
        - asset: fonts/MorpheusIcons.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: JetbrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
          weight: 400